const {chromium}=require(process.env.RIVALS_PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const out=path.resolve(__dirname,'../Logs'),result={errors:[],checks:[]};
const check=(value,label)=>{assert.ok(value,label);result.checks.push(label);console.log('UI_CHECK '+label);};
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.RIVALS_CHROME,headless:true,args:['--enable-unsafe-swiftshader','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows']});
 async function open(){const context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));page.on('console',m=>{if(/^(InvalidOperationException|NullReferenceException|MissingReferenceException|ArgumentException):/.test(m.text()))result.errors.push(m.text());});await page.goto((process.env.RIVALS_WEB_URL||'http://localhost:8184/')+'?diagnostics=1&v=interface');await page.waitForFunction(()=>window.rivalsLobbyState?.ready&&!window.rivalsLobbyState.busy,null,{timeout:120000});return {page,context};}
 const state=page=>page.evaluate(()=>window.rivalsDiagnostics);
 try{
  const host=await open(),client=await open();
  await host.page.locator('#player-name').fill('奶茶貓貓');
  check(await host.page.locator('#room-name').textContent()==='奶茶貓貓的房間','name edit immediately updates room preview');
  check(await host.page.locator('#room-name').evaluate(el=>el.tagName==='OUTPUT'&&!el.isContentEditable),'room name has no editable field');
  await host.page.waitForFunction(()=>window.rivalsLobbyState.room==='奶茶貓貓的房間');
  await host.page.locator('#random-name').click();await host.page.waitForTimeout(500);
  check(await host.page.locator('#room-name').textContent()===(await host.page.locator('#player-name').inputValue())+'的房間','random name also updates room preview');
  await host.page.locator('#player-name').fill('奶茶貓貓');
  await host.page.screenshot({path:path.join(out,'ui-web-lobby.png')});
  await host.page.locator('#create-room').click();
  await host.page.waitForFunction(()=>window.rivalsDiagnostics?.phase===1,null,{timeout:90000});
  await host.page.screenshot({path:path.join(out,'ui-web-countdown.png')});
  await client.page.waitForFunction(()=>window.rivalsLobbyState.rooms.some(r=>r.name==='奶茶貓貓的房間'),null,{timeout:20000});
  result.room=await client.page.evaluate(()=>window.rivalsLobbyState.rooms.find(r=>r.name==='奶茶貓貓的房間'));
  check(result.room.id!==result.room.name,'unique room connection id separate from host display name');
  await client.page.locator('#player-name').fill('布丁兔兔');await client.page.screenshot({path:path.join(out,'ui-web-room-list.png')});
  await client.page.locator('.room-row').filter({has:client.page.locator('strong',{hasText:'奶茶貓貓的房間'})}).getByRole('button',{name:'加入房間',exact:true}).click();
  await client.page.waitForFunction(()=>window.rivalsDiagnostics?.phase===2,null,{timeout:90000});
  await host.page.waitForFunction(()=>window.rivalsDiagnostics?.players.filter(p=>!p.bot).length===2,null,{timeout:15000});
  check((await state(client.page)).players.some(p=>p.name==='奶茶貓貓')&&(await state(client.page)).players.some(p=>p.name==='布丁兔兔'),'real room joins with both custom names');
  const box=await host.page.locator('canvas').boundingBox();await host.page.bringToFront();await host.page.mouse.click(box.x+box.width/2,box.y+box.height/2);
  let near=await state(host.page),self=near.players.find(p=>p.seat===near.localSeat);
  const friend=near.players.find(p=>p.seat!==self.seat&&p.health>0&&p.distance<12&&p.distance>2);
  check(!!friend,'a nearby living teammate is available for name presentation');
  const yaw=Math.atan2(friend.position.x-self.position.x,friend.position.z-self.position.z)*180/Math.PI;
  await host.page.evaluate(({x,y})=>document.dispatchEvent(new MouseEvent('mousemove',{movementX:x,movementY:y,bubbles:true})),{x:(yaw-near.look.x)/.12,y:-near.look.y/.12});
  await host.page.waitForTimeout(200);near=await state(host.page);result.near=near;
  check(near.players.some(p=>p.nameVisible)&&near.players.every(p=>!p.nameVisible||(p.distance<14&&p.health>0)),'nearby labels limited to living players within 14m');
  await host.page.screenshot({path:path.join(out,'ui-web-near-names.png')});
  await host.page.waitForFunction(()=>window.rivalsDiagnostics?.killFeed?.length>0,null,{timeout:75000});
  const feed=await state(host.page);result.feedHost=feed;
  check(feed.killFeed.length<=4&&feed.killFeed.every(e=>e.killer&&e.victim&&e.killerTeam!==e.victimTeam),'kill feed has named opponents and team colors');
  check(new Set(feed.killFeed.map(e=>e.sequence)).size===feed.killFeed.length,'one record per elimination');
  check(feed.players.every(p=>!p.nameVisible||(p.distance<14&&p.health>0)),'dead and distant player names are hidden');
  const seq=feed.killFeed[0].sequence;
  await client.page.waitForFunction(seq=>window.rivalsDiagnostics.killFeed.some(e=>e.sequence===seq),seq,{timeout:5000});
  const clientState=await state(client.page);result.feedClient=clientState;
  const a=feed.killFeed.find(e=>e.sequence===seq),b=clientState.killFeed.find(e=>e.sequence===seq);delete a.remaining;delete b.remaining;
  assert.deepEqual(a,b);check(true,'both clients receive the same killer victim weapon and teams');
  await host.page.screenshot({path:path.join(out,'ui-web-combat.png')});await client.page.screenshot({path:path.join(out,'ui-web-client.png')});
  await client.page.bringToFront();const clientBox=await client.page.locator('canvas').boundingBox();await client.page.mouse.click(clientBox.x+clientBox.width/2,clientBox.y+clientBox.height/2);await client.page.keyboard.press('Escape');await client.page.waitForTimeout(250);await client.page.screenshot({path:path.join(out,'ui-web-pause.png')});
  await client.page.mouse.click(clientBox.x+clientBox.width*.5,clientBox.y+clientBox.height*445/720);
  await client.page.waitForFunction(()=>window.rivalsLobbyState?.visible&&window.rivalsLobbyState.ready&&!window.rivalsLobbyState.busy,null,{timeout:30000});
  const duplicate=await open();await duplicate.page.locator('#player-name').fill('奶茶貓貓');await duplicate.page.locator('#create-room').click();
  await duplicate.page.waitForFunction(()=>window.rivalsDiagnostics?.players?.length===8,null,{timeout:60000});
  await client.page.waitForFunction(()=>window.rivalsLobbyState.rooms.filter(r=>r.name==='奶茶貓貓的房間').length===2,null,{timeout:20000});
  const listings=await client.page.evaluate(()=>window.rivalsLobbyState.rooms.filter(r=>r.name==='奶茶貓貓的房間'));result.duplicateRooms=listings;
  check(new Set(listings.map(r=>r.id)).size===2,'same-name hosts can create separate rooms');
  const second=listings.find(r=>r.id!==result.room.id);
  await client.page.locator('.room-row[data-room-id="'+second.id+'"]').getByRole('button',{name:'加入房間',exact:true}).click();
  await duplicate.page.waitForFunction(()=>window.rivalsDiagnostics.players.filter(p=>!p.bot).length===2,null,{timeout:30000});
  check((await state(host.page)).players.filter(p=>!p.bot).length===1,'selecting duplicate title joins only the chosen room');
  check(result.errors.length===0,'no browser or Unity runtime errors');
  result.ok=true;console.log('WEB_INTERFACE_OK');
 }finally{fs.writeFileSync(path.join(out,'ui-web-check.json'),JSON.stringify(result,null,2));await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
